version: '3.8'

services:
  # API Gateway (Nginx)
  api-gateway:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /tmp/jwt-secret.key:/run/secrets/jwt-secret:ro
    environment:
      - JWT_SECRET_FILE=/run/secrets/jwt-secret
    command: [ "nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf" ]
    depends_on:
      - auth-service
      - payment-service
      - notification-service
    networks:
      - paypal-network

  # Authentication Service
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - JWT_SECRET_FILE=/run/secrets/jwt-secret
    volumes:
      - /tmp/jwt-secret.key:/run/secrets/jwt-secret:ro
    networks:
      - paypal-network

  # Payment Service  
  payment-service:
    build: ./payment-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - AUTH_SERVICE_URL=http://auth-service:3001
      - NOTIFICATION_SERVICE_URL=http://notification-service:3003
      - JWT_SECRET_FILE=/run/secrets/jwt-secret
    volumes:
      - /tmp/jwt-secret.key:/run/secrets/jwt-secret:ro
    depends_on:
      - auth-service
      - notification-service
    networks:
      - paypal-network

  # Notification Service
  notification-service:
    build: ./notification-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - JWT_SECRET_FILE=/run/secrets/jwt-secret
    volumes:
      - /tmp/jwt-secret.key:/run/secrets/jwt-secret:ro
    networks:
      - paypal-network

networks:
  paypal-network:
    driver: bridge
