apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: paypal-clone
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        upstream auth-service {
            server auth-service:3001;
        }
        upstream payment-service {
            server payment-service:3002;
        }
        upstream notification-service {
            server notification-service:3003;
        }
        server {
            listen 80;
            location /health {
                return 200 '{"status":"healthy","service":"api-gateway"}';
                add_header Content-Type application/json;
            }
            location /api/auth/ {
                proxy_pass http://auth-service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            location /api/payment/ {
                proxy_pass http://payment-service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            location /api/notification/ {
                proxy_pass http://notification-service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: paypal-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: paypal-clone
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
