apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: paypal-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: payment-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3001"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:3003"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: paypal-clone
spec:
  selector:
    app: payment-service
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP
